use_frameworks!

platform :ios, '10.0'

target 'XYModuleB_Example' do
  pod 'XYModuleB', :path => '../'

  target 'XYModuleB_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
